Repository ZenBit-Tech/CodeCrafters_be, pull requests merged in 2025-01, with the labels that each got.

#55 Feat/upload customer sign
  src/app.module.ts
  src/common/database/entities/customer-sign.entity.ts
  src/common/database/entities/customer.entity.ts
  src/modules/customers/customers.controller.ts
  src/modules/customers/customers.module.ts
  src/modules/customers/customers.service.ts
  src/modules/orders/interfaces/orderDetails.ts
  src/modules/orders/orders.service.ts
Labels: enhancement

#56 + Create: lock smartLock endpoint
  src/common/database/entities/order.entity.ts
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
Labels: enhancement

#57 Fix/team management
  src/modules/user/dispatcher/dispatcher.service.ts
  src/modules/user/dispatcher/dto/update-dispatcher.dto.ts
  src/modules/user/driver/driver.service.ts
  src/modules/user/driver/dto/update-driver.dto.ts
  src/modules/user/user.service.ts
Labels: bug

#54 Feat/driver to dispatcher be
  src/common/types/routeInformResponse.ts
  src/common/utils/transformRouteObject.ts
  src/modules/orders/dto/order.dto.ts
  src/modules/orders/dto/user.dto.ts
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
  src/modules/orders/types.ts
  src/modules/route/route.service.ts
  src/modules/route/types.ts
Labels: enhancement

#58 feat: add endpoint to fetch orders by route based on order ID
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
Labels: enhancement

#60 fix: added changing of orders status related to the route
  src/common/enums/enums.ts
  src/modules/route/route.service.ts
Labels: bug, enhancement

#61 + Create: readme file
  README.md
Labels: documentation
